kind: pipeline
name: default

workspace:
  path: /kiny-tech

volumes:
  - name: webroot
    host:
      path: /root/www
  - name: pnpm-cache
    host:
      path: /root/.pnpm-cache

trigger:
  branch:
    - master

steps:
  - name: build
    image: paperplanecc/baseline-node20:2025.11.30
    volumes:
      - name: pnpm-cache
        path: /kiny-tech/.pnpm-store
    commands:
      - pnpm i
      - pnpm build

  - name: deploy-upload-cdn
    image: plugins/s3
    settings:
      endpoint:
        from_secret: S3_ENDPOINT
      region:
        from_secret: S3_REGION
      bucket:
        from_secret: S3_BUCKET_NAME
      access_key:
        from_secret: S3_ACCESS_KEY_ID
      secret_key:
        from_secret: S3_SECRET_ACCESS_KEY
      source: ./dist/**/*
      target: /paperplane-kiny
      strip_prefix: dist

  - name: deploy
    image: alpine:3.20
    volumes:
      - name: webroot
        path: /webroot
    commands:
      - mkdir -p /webroot/kiny/
      - rm -rf /webroot/kiny/*
      - cp -rf ./dist/* /webroot/kiny/
